apiVersion: v1
kind: Service
metadata:
  name: flask-demo-test-service
spec:
  selector:
    app: flask-demo-test-app
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
matadata:
  name: flask-pv-claim
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-test-app
spec:
  selector:
    matchLabels:
      app: flask-demo-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-demo-test-app
    spec:
      volumes:
        - name: flask-pv-storage
          persistentVolumeClaim:
            claimName: flask-pv-claim
      containers:
        - name: flask-demo-test-app
          image: sreelk589/flask-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/app"
              name: flask-pv-storage
